### ISSUE TITLE
unable to fetch materials/pycharm-documentation.pdf

### ISSUE THREAD

**Issue by karolszk** [t-redactyl/simple-rag-document-qa#3]
Hello,

git-lfs fetch returns the following error:

Fetching reference refs/heads/main batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. error: failed to fetch some objects from 'https://github.com/t-redactyl/simple-rag-document-qa.git/info/lfs'

**Comment by t-redactyl** [comment]
Turns out the issue was that I had exceeded my LFS limit. I've added more to my plan - it should be working now. Thanks very much for raising this!

**Comment by karolszk** [comment]
Thank you. Now it works perfectly.
